apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: roboshop
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb-headless-svc
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  ports:
  - port: 27017
    name: database
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: database
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb-svc
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  ports:
  - port: 27017
    name: database
  selector:
    project: roboshop
    component: mongodb
    tier: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  serviceName: "mongodb-headless-svc" # this should be headless service
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: rajesh947/mongodb:v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop"
      resources:
        requests:
          storage: 2Gi