apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    component: mysql
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: roboshop
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-svc
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  serviceName: "mysql-headless-svc" # this should be headless service
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: rajesh947/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop"
      resources:
        requests:
          storage: 2Gi